"""
dashboard/build_dashboard_data.py — bake the dashboard's data file (Phase 5).

Produces dashboard/data.js:  window.DASHBOARD_DATA = { ... };

Why a .js file (not JSON fetched at runtime): the dashboard is meant to open as a
plain local file (file://) with no server. Browsers block fetch() of local files,
but a <script src="data.js"> that assigns a global works everywhere. So we bake the
data in at build time.

This is a REPORTING artifact, built AFTER the pipeline has run. It joins the frozen
ground-truth labels back in (from test_set.json) purely so the analyst can SEE how
each machine decision compares to truth — exactly what eval/metrics.py does. The
pipeline itself still never sees a label (data/pipeline_output.json has none); there
is no leakage path into the decision (rules.md R4).

Run:  python3 dashboard/build_dashboard_data.py   (after run_pipeline.py)
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from audit.logger import read_trail  # noqa: E402
from eval.metrics import compute_metrics  # noqa: E402
from pipeline.common import (  # noqa: E402
    DASHBOARD_DIR, PIPELINE_OUTPUT_PATH, TEST_SET_PATH, load_families, load_thresholds,
)


def _families_reference():
    """Display names + per-field 'why it matters' text for the checklist."""
    ref = {}
    for key, fam in load_families().items():
        ref[key] = {
            "display_name": fam.get("display_name", key),
            "description": fam.get("description", ""),
            "fields": {
                fname: {"required": bool(fc.get("required", False)),
                        "weight": fc.get("weight"), "why": fc.get("why", "")}
                for fname, fc in fam.get("evidence", {}).items()
            },
        }
    return ref


def build():
    with open(PIPELINE_OUTPUT_PATH, "r", encoding="utf-8") as f:
        pipeline = json.load(f)
    with open(TEST_SET_PATH, "r", encoding="utf-8") as f:
        test_set = json.load(f)

    results = pipeline["results"]
    metrics = compute_metrics(test_set, results)

    # ground-truth join (display only) + audit entries per dispute
    gt = {c["dispute_id"]: c for c in test_set["cases"]}
    trail = read_trail()
    audit_by_id = {}
    for e in trail:
        audit_by_id.setdefault(e.get("dispute_id"), []).append(e)

    cases = []
    for r in results:
        did = r["dispute_id"]
        truth = gt.get(did, {})
        case = dict(r)  # pipeline decision (already label-free)
        # attach display-only reference info
        case["ground_truth"] = truth.get("ground_truth")
        case["gt_rationale"] = truth.get("gt_rationale")
        case["family_expected"] = truth.get("family_expected")
        case["decision_matches_truth"] = _matches(r["recommendation"], truth.get("ground_truth"))
        case["audit"] = audit_by_id.get(did, [])
        cases.append(case)

    payload = {
        "generated_at": pipeline.get("generated_at"),
        "backend": pipeline.get("backend"),
        "n_cases": len(cases),
        "thresholds": load_thresholds(),
        "families": _families_reference(),
        "metrics": metrics,
        "cases": cases,
    }

    DASHBOARD_DIR.mkdir(parents=True, exist_ok=True)
    out_path = DASHBOARD_DIR / "data.js"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_dashboard_data.py — do not edit by hand.\n")
        f.write("// Reporting artifact: joins ground-truth labels for DISPLAY only.\n")
        f.write("window.DASHBOARD_DATA = ")
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    print(f"Wrote {out_path}  ({len(cases)} cases, backend='{payload['backend']}').")
    return payload


def _matches(rec, ground_truth):
    """Did the recommendation align with truth? (for the honest-eval display)
    Mirrors eval/metrics.py: positive = submit/caveats; borderline->caveats is 'ok';
    n/a->punt is 'ok'. Returns True / False / None (not applicable)."""
    if ground_truth == "should_win":
        return rec in ("submit", "submit_with_caveats")
    if ground_truth == "should_lose":
        return rec == "do_not_submit"
    if ground_truth == "borderline":
        return rec == "submit_with_caveats"
    if ground_truth == "n/a":
        return rec == "punt"
    return None


if __name__ == "__main__":
    build()
